-- типы вагонов
CREATE TABLE types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (60) UNIQUE NOT NULL   -- наименование
);

-- вагоны
CREATE TABLE wagons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR (7) UNIQUE NOT NULL,             -- номер
    type_id BIGINT NOT NULL REFERENCES types (id),  -- тип вагона
    tare_weight REAL NOT NULL,                      -- вес тары
    load_capacity REAL NOT NULL                     -- грузоподъемность
);

-- роли
CREATE TABLE roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR UNIQUE NOT NULL    -- наименование
);

-- пользователи
CREATE TABLE people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(60) UNIQUE NOT NULL,              -- логин
    password VARCHAR (255) NOT NULL,                -- пароль
    role_id BIGINT NOT NULL REFERENCES roles(id)    -- роль
);

-- станции
CREATE TABLE stations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (100) NOT NULL -- наименование
);

 -- пути
CREATE TABLE pathways (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id BIGINT NOT NULL REFERENCES stations (id) ON DELETE CASCADE,  -- станция
    number INT NOT NULL                                                     -- номер
);

-- грузы (справочник номенклатур грузов)
CREATE TABLE cargos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) UNIQUE NOT NULL,   -- код
    name VARCHAR (100) NOT NULL         -- наименование
);

-- документы (натурный лист для приема вагонов)
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number INT NOT NULL,                             -- порядковый номер
    wagon_number VARCHAR (7) NOT NULL,                      -- номер вагона
    cargo_id BIGINT NOT NULL REFERENCES cargos (id),        -- номенклатура груза
    cargo_weight REAL NOT NULL,                             -- вес груза
    wagon_weight REAL NOT NULL,                             -- вес вагона
    pathway_id BIGINT NOT NULL REFERENCES pathways (id),    -- путь
    departure_date TIMESTAMP                                -- дата убытия
);

INSERT INTO types (name) VALUES ('Тип 1'), ('Тип 2'), ('Тип 3');

INSERT INTO wagons(number, type_id, tare_weight, load_capacity) VALUES ('1111122', 1, 12.3, 15.0),
('6666677', 3, 18.7, 20.1), ('1234567', 1, 23.0, 56.3), ('7654321', 1, 12.1, 15.1),
('1111111', 1, 1.1, 11.1), ('2222222', 2, 2.2, 12.2), ('3333333', 3, 3.3, 13.3),
('4444444', 3, 4.4, 14.1), ('5555555', 2, 7.8, 10.9),('6666666', 3, 12.1, 23.2), ('7777777', 1, 13.1, 14.1);

INSERT INTO roles(name) VALUES ('GUEST'), ('MODERATOR'), ('ADMIN');

INSERT INTO people (login, password, role_id) VALUES ('admin', '1111', 3), ('tom', '1111', 3), ('alice', '1234', 2), ('bob', '5678', 1);

INSERT INTO stations(name) VALUES ('Первая станция'), ('Вторая станция'), ('Третья станция');

INSERT INTO pathways(station_id, number) VALUES (1, 1), (1, 3), (1, 5), (2, 1), (2, 2), (3, 7), (3, 9);

INSERT INTO cargos(code, name) VALUES ('001', 'Груз 1'), ('002', 'Груз 2');

INSERT INTO documents(serial_number, wagon_number, cargo_id, cargo_weight, wagon_weight, pathway_id) VALUES
(1, '3333333', 1, 55.1, 56.7, 4), (2, '1111111', 1, 123.1, 155.5, 4), (3, '1111122', 1, 23.1, 55.5, 4),
(1, '2222222', 1, 33.1, 36.6, 5);

INSERT INTO documents(serial_number, wagon_number, cargo_id, cargo_weight, wagon_weight, pathway_id, departure_date)
VALUES (2, '7777777', 1, 17.1, 21.5, 5, now());