-- типы вагонов
CREATE TABLE types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (60) UNIQUE NOT NULL   -- наименование
);

-- вагоны
CREATE TABLE wagons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR (7) UNIQUE NOT NULL,             -- номер
    type_id BIGINT NOT NULL REFERENCES types (id),  -- тип вагона
    tare_weight REAL NOT NULL,                      -- вес тары
    load_capacity REAL NOT NULL                     -- грузоподъемность
);

-- роли
CREATE TABLE roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR UNIQUE NOT NULL    -- наименование
);

-- пользователи
CREATE TABLE people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(60) UNIQUE NOT NULL,              -- логин
    password VARCHAR (255) NOT NULL,                -- пароль
    role_id BIGINT NOT NULL REFERENCES roles(id)    -- роль
);

-- станции
CREATE TABLE stations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (100) NOT NULL -- наименование
);

 -- пути
CREATE TABLE pathways (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id BIGINT NOT NULL REFERENCES stations (id) ON DELETE CASCADE,  -- станция
    number INT NOT NULL                                                     -- номер
);

-- грузы (справочник номенклатур грузов)
CREATE TABLE cargos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) UNIQUE NOT NULL,   -- код
    name VARCHAR (100) NOT NULL         -- наименование
);

-- документы (натурный лист для приема вагонов)
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number INT NOT NULL,                             -- порядковый номер
    wagon_number VARCHAR (7) NOT NULL,                      -- номер вагона
    cargo_id BIGINT NOT NULL REFERENCES cargos (id),        -- номенклатура груза
    cargo_weight REAL NOT NULL,                             -- вес груза
    wagon_weight REAL NOT NULL,                             -- вес вагона
    pathway_id BIGINT NOT NULL REFERENCES pathways (id),    -- путь
    departure_date TIMESTAMP                                -- дата убытия
);

INSERT INTO roles(name) VALUES ('GUEST'), ('MODERATOR'), ('ADMIN');

INSERT INTO people(login, password, role_id) VALUES ('tom', '1111', 3), ('alice', '1234', 2),
('bob', '5678', 1);

